language: php
php:
  - '7.4'
cache:
    directories:
        - $HOME/.composer/cache
env:
    global:
        - XDEBUG_MODE=coverage
install:
    - composer install
script:
    - symfony check:security
    - composer unit:test
    - composer analyse