#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/v1/auth
app.swagger_ui:
    path: /docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
